/***************************************************************
This code was generated by Spiral 6.0 beta, www.spiral.net --
Copyright (c) 2005-2008, Carnegie Mellon University.
All rights reserved.
The code is distributed under the GNU General Public License (GPL)
(see http://www.gnu.org/copyleft/gpl.html)

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*AS IS* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************/

#include "include/omega64.h"

void init_sub() {
}

void sub(double  *Y, double  *X, double h) {
    
    *(Y) = *(X);
    *((Y + 1)) = *((X + 1));
    *((Y + 2)) = *((X + 2));
    *((Y + 3)) = -(((1/h)**(X)));
    *((Y + 4)) = -(((1/h)**((X + 1))));
    *((Y + 5)) = -(((1/h)**((X + 2))));
    *(Y) = (*(Y) - (h**((X + 3))));
    *((Y + 1)) = (*((Y + 1)) - (h**((X + 4))));
    *((Y + 2)) = (*((Y + 2)) - (h**((X + 5))));
    *((Y + 3)) = (*((Y + 3)) + *((X + 3)));
    *((Y + 4)) = (*((Y + 4)) + *((X + 4)));
    *((Y + 5)) = (*((Y + 5)) + *((X + 5)));
    *(Y) = (*(Y) - *((X + 6)));
    *((Y + 1)) = (*((Y + 1)) - *((X + 7)));
    *((Y + 2)) = (*((Y + 2)) - *((X + 8)));
    *((Y + 3)) = (*((Y + 3)) + ((1/h)**((X + 6))));
    *((Y + 4)) = (*((Y + 4)) + ((1/h)**((X + 7))));
    *((Y + 5)) = (*((Y + 5)) + ((1/h)**((X + 8))));
    *(Y) = *(Y);
    *((Y + 1)) = *((Y + 1));
    *((Y + 2)) = *((Y + 2));
    *((Y + 3)) = *((Y + 3));
    *((Y + 4)) = *((Y + 4));
    *((Y + 5)) = *((Y + 5));
}
